-- Таблица для хранения информации о лауреатах
CREATE TABLE laureates
(
    id                INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    origin_id         INT,
    firstname         VARCHAR(100) NOT NULL,
    surname           VARCHAR(100) NOT NULL,
    born              DATE,
    died              DATE,
    born_country      VARCHAR(100),
    born_country_code VARCHAR(10),
    born_city         VARCHAR(100),
    died_country      VARCHAR(100),
    died_country_code VARCHAR(10),
    died_city         VARCHAR(100),
    gender            VARCHAR(10)
);

-- Таблица для хранения информации о призах, связанных с лауреатом
CREATE TABLE prizes
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    laureate_id INT REFERENCES laureates (id) ON DELETE SET NULL,
    year        INT         NOT NULL,
    category    VARCHAR(50) NOT NULL,
    share       INT,
    motivation  TEXT
);

-- Таблица для хранения информации о членствах/афилиациях, связанных с призом
CREATE TABLE affiliations
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    prize_id INT REFERENCES prizes (id) ON DELETE SET NULL,
    name     VARCHAR(255),
    city     VARCHAR(100),
    country  VARCHAR(100)
);
