/*
 * This file is generated by jOOQ.
 */
package ru.paskal.laba2.entities.tables.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.paskal.laba2.entities.tables.Keys;
import ru.paskal.laba2.entities.tables.Laba2;
import ru.paskal.laba2.entities.tables.tables.records.LaureatesMetadataRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LaureatesMetadata extends TableImpl<LaureatesMetadataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>laba2.laureates_metadata</code>
     */
    public static final LaureatesMetadata LAUREATES_METADATA = new LaureatesMetadata();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LaureatesMetadataRecord> getRecordType() {
        return LaureatesMetadataRecord.class;
    }

    /**
     * The column <code>laba2.laureates_metadata.id</code>.
     */
    public final TableField<LaureatesMetadataRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>laba2.laureates_metadata.last_updated</code>.
     */
    public final TableField<LaureatesMetadataRecord, LocalDateTime> LAST_UPDATED = createField(DSL.name("last_updated"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>laba2.laureates_metadata.laureates_count</code>.
     */
    public final TableField<LaureatesMetadataRecord, Integer> LAUREATES_COUNT = createField(DSL.name("laureates_count"), SQLDataType.INTEGER.nullable(false), this, "");

    private LaureatesMetadata(Name alias, Table<LaureatesMetadataRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LaureatesMetadata(Name alias, Table<LaureatesMetadataRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>laba2.laureates_metadata</code> table reference
     */
    public LaureatesMetadata(String alias) {
        this(DSL.name(alias), LAUREATES_METADATA);
    }

    /**
     * Create an aliased <code>laba2.laureates_metadata</code> table reference
     */
    public LaureatesMetadata(Name alias) {
        this(alias, LAUREATES_METADATA);
    }

    /**
     * Create a <code>laba2.laureates_metadata</code> table reference
     */
    public LaureatesMetadata() {
        this(DSL.name("laureates_metadata"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Laba2.LABA2;
    }

    @Override
    public Identity<LaureatesMetadataRecord, Integer> getIdentity() {
        return (Identity<LaureatesMetadataRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LaureatesMetadataRecord> getPrimaryKey() {
        return Keys.LAUREATES_METADATA_PKEY;
    }

    @Override
    public LaureatesMetadata as(String alias) {
        return new LaureatesMetadata(DSL.name(alias), this);
    }

    @Override
    public LaureatesMetadata as(Name alias) {
        return new LaureatesMetadata(alias, this);
    }

    @Override
    public LaureatesMetadata as(Table<?> alias) {
        return new LaureatesMetadata(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LaureatesMetadata rename(String name) {
        return new LaureatesMetadata(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LaureatesMetadata rename(Name name) {
        return new LaureatesMetadata(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LaureatesMetadata rename(Table<?> name) {
        return new LaureatesMetadata(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LaureatesMetadata where(Condition condition) {
        return new LaureatesMetadata(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LaureatesMetadata where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LaureatesMetadata where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LaureatesMetadata where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LaureatesMetadata where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LaureatesMetadata where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LaureatesMetadata where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LaureatesMetadata where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LaureatesMetadata whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LaureatesMetadata whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
