/*
 * This file is generated by jOOQ.
 */
package ru.paskal.laba2.entities.tables.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.paskal.laba2.entities.tables.tables.LaureatesMetadata;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LaureatesMetadataRecord extends UpdatableRecordImpl<LaureatesMetadataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>laba2.laureates_metadata.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>laba2.laureates_metadata.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>laba2.laureates_metadata.last_updated</code>.
     */
    public void setLastUpdated(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>laba2.laureates_metadata.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>laba2.laureates_metadata.laureates_count</code>.
     */
    public void setLaureatesCount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>laba2.laureates_metadata.laureates_count</code>.
     */
    public Integer getLaureatesCount() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LaureatesMetadataRecord
     */
    public LaureatesMetadataRecord() {
        super(LaureatesMetadata.LAUREATES_METADATA);
    }

    /**
     * Create a detached, initialised LaureatesMetadataRecord
     */
    public LaureatesMetadataRecord(Integer id, LocalDateTime lastUpdated, Integer laureatesCount) {
        super(LaureatesMetadata.LAUREATES_METADATA);

        setId(id);
        setLastUpdated(lastUpdated);
        setLaureatesCount(laureatesCount);
        resetChangedOnNotNull();
    }
}
