/*
 * This file is generated by jOOQ.
 */
package ru.paskal.laba2.entities.tables.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.paskal.laba2.entities.tables.tables.Prizes;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrizesRecord extends UpdatableRecordImpl<PrizesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>laba2.prizes.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>laba2.prizes.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>laba2.prizes.laureate_id</code>.
     */
    public void setLaureateId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>laba2.prizes.laureate_id</code>.
     */
    public Integer getLaureateId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>laba2.prizes.year</code>.
     */
    public void setYear(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>laba2.prizes.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>laba2.prizes.category</code>.
     */
    public void setCategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>laba2.prizes.category</code>.
     */
    public String getCategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>laba2.prizes.share</code>.
     */
    public void setShare(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>laba2.prizes.share</code>.
     */
    public Integer getShare() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>laba2.prizes.motivation</code>.
     */
    public void setMotivation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>laba2.prizes.motivation</code>.
     */
    public String getMotivation() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrizesRecord
     */
    public PrizesRecord() {
        super(Prizes.PRIZES);
    }

    /**
     * Create a detached, initialised PrizesRecord
     */
    public PrizesRecord(Integer id, Integer laureateId, Integer year, String category, Integer share, String motivation) {
        super(Prizes.PRIZES);

        setId(id);
        setLaureateId(laureateId);
        setYear(year);
        setCategory(category);
        setShare(share);
        setMotivation(motivation);
        resetChangedOnNotNull();
    }
}
