/*
 * This file is generated by jOOQ.
 */
package ru.paskal.laba2.entities.tables.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.paskal.laba2.entities.tables.tables.UserEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserEntityRecord extends UpdatableRecordImpl<UserEntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>laba2.user_entity.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>laba2.user_entity.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>laba2.user_entity.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>laba2.user_entity.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>laba2.user_entity.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>laba2.user_entity.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>laba2.user_entity.role</code>.
     */
    public void setRole(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>laba2.user_entity.role</code>.
     */
    public String getRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>laba2.user_entity.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>laba2.user_entity.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserEntityRecord
     */
    public UserEntityRecord() {
        super(UserEntity.USER_ENTITY);
    }

    /**
     * Create a detached, initialised UserEntityRecord
     */
    public UserEntityRecord(Integer id, Boolean enabled, String password, String role, String username) {
        super(UserEntity.USER_ENTITY);

        setId(id);
        setEnabled(enabled);
        setPassword(password);
        setRole(role);
        setUsername(username);
        resetChangedOnNotNull();
    }
}
