/*
 * This file is generated by jOOQ.
 */
package ru.paskal.laba2.entities.tables;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.paskal.laba2.entities.tables.tables.Affiliations;
import ru.paskal.laba2.entities.tables.tables.Laureates;
import ru.paskal.laba2.entities.tables.tables.LaureatesMetadata;
import ru.paskal.laba2.entities.tables.tables.Prizes;
import ru.paskal.laba2.entities.tables.tables.UserEntity;
import ru.paskal.laba2.entities.tables.tables.records.AffiliationsRecord;
import ru.paskal.laba2.entities.tables.tables.records.LaureatesMetadataRecord;
import ru.paskal.laba2.entities.tables.tables.records.LaureatesRecord;
import ru.paskal.laba2.entities.tables.tables.records.PrizesRecord;
import ru.paskal.laba2.entities.tables.tables.records.UserEntityRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * laba2.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AffiliationsRecord> AFFILIATIONS_PKEY = Internal.createUniqueKey(Affiliations.AFFILIATIONS, DSL.name("affiliations_pkey"), new TableField[] { Affiliations.AFFILIATIONS.ID }, true);
    public static final UniqueKey<LaureatesRecord> LAUREATES_PKEY = Internal.createUniqueKey(Laureates.LAUREATES, DSL.name("laureates_pkey"), new TableField[] { Laureates.LAUREATES.ID }, true);
    public static final UniqueKey<LaureatesMetadataRecord> LAUREATES_METADATA_PKEY = Internal.createUniqueKey(LaureatesMetadata.LAUREATES_METADATA, DSL.name("laureates_metadata_pkey"), new TableField[] { LaureatesMetadata.LAUREATES_METADATA.ID }, true);
    public static final UniqueKey<PrizesRecord> PRIZES_PKEY = Internal.createUniqueKey(Prizes.PRIZES, DSL.name("prizes_pkey"), new TableField[] { Prizes.PRIZES.ID }, true);
    public static final UniqueKey<UserEntityRecord> USER_ENTITY_PKEY = Internal.createUniqueKey(UserEntity.USER_ENTITY, DSL.name("user_entity_pkey"), new TableField[] { UserEntity.USER_ENTITY.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AffiliationsRecord, PrizesRecord> AFFILIATIONS__AFFILIATIONS_PRIZE_ID_FKEY = Internal.createForeignKey(Affiliations.AFFILIATIONS, DSL.name("affiliations_prize_id_fkey"), new TableField[] { Affiliations.AFFILIATIONS.PRIZE_ID }, Keys.PRIZES_PKEY, new TableField[] { Prizes.PRIZES.ID }, true);
    public static final ForeignKey<PrizesRecord, LaureatesRecord> PRIZES__PRIZES_LAUREATE_ID_FKEY = Internal.createForeignKey(Prizes.PRIZES, DSL.name("prizes_laureate_id_fkey"), new TableField[] { Prizes.PRIZES.LAUREATE_ID }, Keys.LAUREATES_PKEY, new TableField[] { Laureates.LAUREATES.ID }, true);
}
