/*
 * This file is generated by jOOQ.
 */
package ru.paskal.laba2.entities.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.paskal.laba2.entities.tables.tables.Affiliations;
import ru.paskal.laba2.entities.tables.tables.Laureates;
import ru.paskal.laba2.entities.tables.tables.LaureatesMetadata;
import ru.paskal.laba2.entities.tables.tables.Prizes;
import ru.paskal.laba2.entities.tables.tables.UserEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Laba2 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>laba2</code>
     */
    public static final Laba2 LABA2 = new Laba2();

    /**
     * The table <code>laba2.affiliations</code>.
     */
    public final Affiliations AFFILIATIONS = Affiliations.AFFILIATIONS;

    /**
     * The table <code>laba2.laureates</code>.
     */
    public final Laureates LAUREATES = Laureates.LAUREATES;

    /**
     * The table <code>laba2.laureates_metadata</code>.
     */
    public final LaureatesMetadata LAUREATES_METADATA = LaureatesMetadata.LAUREATES_METADATA;

    /**
     * The table <code>laba2.prizes</code>.
     */
    public final Prizes PRIZES = Prizes.PRIZES;

    /**
     * The table <code>laba2.user_entity</code>.
     */
    public final UserEntity USER_ENTITY = UserEntity.USER_ENTITY;

    /**
     * No further instances allowed
     */
    private Laba2() {
        super("laba2", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Affiliations.AFFILIATIONS,
            Laureates.LAUREATES,
            LaureatesMetadata.LAUREATES_METADATA,
            Prizes.PRIZES,
            UserEntity.USER_ENTITY
        );
    }
}
