/*
 * This file is generated by jOOQ.
 */
package ru.paskal.laba2.entities.tables;


import ru.paskal.laba2.entities.tables.tables.Affiliations;
import ru.paskal.laba2.entities.tables.tables.Laureates;
import ru.paskal.laba2.entities.tables.tables.LaureatesMetadata;
import ru.paskal.laba2.entities.tables.tables.Prizes;
import ru.paskal.laba2.entities.tables.tables.UserEntity;


/**
 * Convenience access to all tables in laba2.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>laba2.affiliations</code>.
     */
    public static final Affiliations AFFILIATIONS = Affiliations.AFFILIATIONS;

    /**
     * The table <code>laba2.laureates</code>.
     */
    public static final Laureates LAUREATES = Laureates.LAUREATES;

    /**
     * The table <code>laba2.laureates_metadata</code>.
     */
    public static final LaureatesMetadata LAUREATES_METADATA = LaureatesMetadata.LAUREATES_METADATA;

    /**
     * The table <code>laba2.prizes</code>.
     */
    public static final Prizes PRIZES = Prizes.PRIZES;

    /**
     * The table <code>laba2.user_entity</code>.
     */
    public static final UserEntity USER_ENTITY = UserEntity.USER_ENTITY;
}
